// import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import AuthModal from "@/modals/AuthModal/AuthModal";

// export const metadata: Metadata = {
//   title: "ToDo App",
//   description: "Generated by create next app",
// };

interface Props {
  children: ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <AuthModal />
        <div className="app_container">
          {children}
        </div>
      </body>
    </html>
  );
}
